#!/usr/bin/env bash

clone_dev_environment() {
    echo "Cloning dev environment into $HOME"
    cd $HOME
    if [ $(git rev-parse --is-inside-work-tree) ]; then
        return
    fi
    git init
    git remote add origin ssh://git@github.com:namolnad/dev-environment.git
    git fetch origin
    git checkout -b master --track origin/master
    cd -
}

create_directories() {
    echo 'Create custom_credentials directory (if not exists)'
    mkdir $HOME/.custom_credentials
    mkdir $HOME/Code
}

display_manual_tasks_remaining() {
    echo """
    Tasks remaining:
    1) Ensure Dropbox syncing is set up
    2) Point development application settings to \"$HOME/Dropbox/.dev_sync\"
    3) Grant full disk access to Alfred
    4) Download latest Pock release: https://github.com/pigigaldi/Pock/releases
    5) Install GPG Suite; set up GPG signing
    6) Set up SSH
    """
}

init_submodules() {
    echo 'Initializing all submodules'
    git submodule update --init --recursive
}

install_automator_tasks() {
    echo 'Installing automator tasks'
    # TODO: Install tasks from Dans-scripts
    # See https://apple.stackexchange.com/questions/343258/how-to-deploy-automator-workflow-to-clients for migration tactics
}

install_dependencies() {
    echo 'Installing gems'
    bundle install
    echo 'Running brew bundle'
    brew bundle
    echo 'Installing FZF'
    yes | $(brew --prefix)/opt/fzf/install
    echo 'Installing Oh My Zsh'
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

install_homebrew() {
    echo 'Checking if homebrew is installed'
    if ! [ -x "$(command -v brew)" ]; then
        echo 'Installing homebrew'
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
}

setup_non_vim_editors() {
    echo 'Installing TabNine for VSCode'
    # TODO: Install TabNine (also for vscode)
}

setup_ruby_environment() {
    echo 'Installing rbenv'
    brew install rbenv
    echo 'Installing global ruby'
    rbenv install -s $(cat ~/.rbenv/version)
    eval "$(rbenv init -)"
    echo 'Installing bundler'
    gem install bundler
    rbenv rehash
}

setup_system_settings() {
    $HOME/.macOS
}

setup_vim() {
    # TODO: Evaluate whether MacVim should be used along with iCompleteMe (and remove vim from Brewfile is so)
    # MacVim install
    # Move mvim script to /usr/local/bin
    # Symlink mvim script to vim
    #####
    # Install plugins
    vim -c 'PluginInstall' -c 'qa!'
}

symlink_customizations() {
    # Remove existing directory symlinks if exists
    rm -rf .oh-my-zsh/custom .vim

    # Setup symlinks
    ln -fs $HOME/.bashrc.symlink $HOME/.bashrc
    ln -fs $HOME/.bash_profile.symlink $HOME/.bash_profile
    ln -fs $HOME/.omz_custom.symlink $HOME/.oh-my-zsh/custom
    ln -fs $HOME/.vim.symlink $HOME/.vim
    ln -fs $HOME/.vimrc.symlink $HOME/.vimrc
    ln -fs $HOME/.xvimrc.symlink $HOME/.xvimrc
    ln -fs $HOME/.zshrc.symlink $HOME/.zshrc
    ln -fs $HOME/.ripgreprc.symlink $HOME/.ripgreprc
}

symlink_scripts() {
    script_home=$HOME/Code/Scripts
    destination=/usr/local/bin

    ln -s $script_home/git-stashfiles $destination
    ln -s $script_home/git-rebase-origin $destination
}

symlink_binaries() {
    ln -s $(xcrun --find sourcekit-lsp) /usr/local/bin/sourcekit-lsp
}

echo 'Bootstrapping machine'

# NOTE: Order is important
create_directories
clone_dev_environment
install_homebrew
setup_ruby_environment
install_dependencies
symlink_customizations
symlink_scripts
setup_system_settings
init_submodules
install_automator_tasks
setup_non_vim_editors
symlink_binaries
display_manual_tasks_remaining
